import Head from "next/head";
import "./globals.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Airbnb Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="https://lauranoesta.com/wp-content/uploads/2019/09/airbnb-logo.png"
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
